package vista;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Angelo
 */
public class VistaInicio extends JFrame {

    /**
     * Creates new form VentanaInicial
     */
    public VistaInicio() {
        ImageIcon icono = new ImageIcon("C:\\Users\\Angelo\\Documents\\ProyectosNB\\Tragamonedas\\src\\imagenes\\ico.png");
        setIconImage(icono.getImage());
        setTitle("Tragamonedas :: $$");
        setResizable(false);
        setSize(600,600);
        setVisible(true);
        setLayout(null); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        botonplay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuSalir = new javax.swing.JMenu();
        itemsalir = new javax.swing.JMenuItem();
        MenuAcercade = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonplay.setFont(new java.awt.Font("Dubai", 3, 14)); // NOI18N
        botonplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PLAY.jpg"))); // NOI18N
        botonplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonplayActionPerformed(evt);
            }
        });
        panel1.add(botonplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 210, 80));
        botonplay.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpeg"))); // NOI18N
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 350, 160));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 310));

        MenuSalir.setText("Opciones🛠️");

        itemsalir.setText("Salir❌");
        MenuSalir.add(itemsalir);

        jMenuBar1.add(MenuSalir);

        MenuAcercade.setText("🚩Acerca de ");

        jMenuItem1.setForeground(new java.awt.Color(0, 102, 255));
        jMenuItem1.setText("Tragamonedas Equipo1");
        MenuAcercade.add(jMenuItem1);

        jMenuBar1.add(MenuAcercade);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonplayActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MenuAcercade;
    public javax.swing.JMenu MenuSalir;
    public javax.swing.JButton botonplay;
    public javax.swing.JMenuItem itemsalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
